# Generated by Django 4.1.2 on 2022-10-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_student_surname_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
