# Generated by Django 4.1.2 on 2022-10-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_teacher_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birthday',
        ),
        migrations.AddField(
            model_name='teacher',
            name='iin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
